## https://docs.gitlab.com/ce/ci/yaml/README.html

###### GENERAL ################################################################
image: node:8.15.1

cache:
  paths:
  - node_modules/
  - pages/node_modules/

###### TEMPLATES ##############################################################
.general: &general
  tags:
    - gitlab-org
  variables:
    GIT_STRATEGY: fetch

.pack-common: &pack-common
  <<: *general
  stage: pack
  environment:
    name: ${CI_COMMIT_REF_NAME}
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - master

###### STAGES #################################################################
stages:
  - install
  - test
  - build
  - pack
  - deploy

###### JOBS ###################################################################
install:
  <<: *general
  stage: install
  cache:
    policy: pull-push
    paths:
      - node_modules
  script:
    - yarn install
  only:
    - master

test:
  <<: *general
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - install
  artifacts:
    paths:
      - coverage
    expire_in: 1 month
  script:
    - yarn test --verbose --forceExit --ci --coverage --colors
  only:
    - master

build:
  <<: *general
  stage: build
  environment:
    name: ${CI_COMMIT_REF_NAME}
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - install
  script:
    - yarn react-build
  artifacts:
    expire_in: 1 week
    paths:
      - build
  only:
    - master

pack:
  <<: *pack-common
  tags:
    - macos
  script:
    - yarn dist-all --publish always

pages:
  <<: *general
  stage: deploy
  cache:
    policy: pull
    paths: []
  dependencies: []
  script:
    - cd pages
    - yarn install
    - yarn build
    - rm -rf ../public
    - mv build ../public
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  only:
    - master
