## https://docs.gitlab.com/ce/ci/yaml/README.html

###### GENERAL ################################################################
image: node:8.15.1

cache:
  paths:
  - node_modules/
  - pages/node_modules/

###### TEMPLATES ##############################################################
.general: &general
  tags:
    - gitlab-org
  variables:
    GIT_STRATEGY: fetch

.release-common: &release-common
  <<: *general
  stage: release
  environment:
    name: ${CI_COMMIT_REF_NAME}
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - react app
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - master
  retry:
    max: 2
    when: always

###### STAGES #################################################################
stages:
  - install
  - test
  - build
  - release
  - deploy

###### JOBS ###################################################################
dependencies:
  <<: *general
  stage: install
  cache:
    policy: pull-push
    paths:
      - node_modules
  script:
    - yarn install
  only:
    - master

jest:
  <<: *general
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - dependencies
  artifacts:
    paths:
      - coverage
    expire_in: 1 month
  script:
    - yarn test --verbose --forceExit --ci --coverage --colors
  only:
    - master

react app:
  <<: *general
  stage: build
  environment:
    name: ${CI_COMMIT_REF_NAME}
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - dependencies
  script:
    - echo "CLIENT_SECRET=${CLIENT_SECRET}" > .env
    - echo 'REACT_APP_PRODUCT_NAME=${npm_package_productName}' >> .env
    - yarn react-build
  artifacts:
    expire_in: 1 week
    paths:
      - .env
      - build
  only:
    - master

mac:
  <<: *release-common
  tags:
    - macos
  script:
    - yarn dist -m --publish always

linux:
  <<: *release-common
  image: electronuserland/builder:10
  script:
    - yarn dist -l --publish always

windows:
  <<: *release-common
  image: electronuserland/builder:wine
  script:
    - yarn dist -w --publish always

pages:
  <<: *general
  stage: deploy
  cache:
    policy: pull
    paths: []
  dependencies: []
  script:
    - cd pages
    - yarn install
    - yarn build
    - rm -rf ../public
    - mv build ../public
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  only:
    - master
