## https://docs.gitlab.com/ce/ci/yaml/README.html

###### GENERAL ################################################################
image: node:8.15.1

cache:
  paths:
  - node_modules/
  - pages/node_modules/

###### TEMPLATES ##############################################################
.general: &general
  tags:
    - gitlab-org
  variables:
    GIT_STRATEGY: fetch

.release-common: &release-common
  <<: *general
  stage: release
  environment:
    name: ${CI_COMMIT_REF_NAME}
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - master
  retry:
    max: 2
    when: always

###### STAGES #################################################################
stages:
  - install
  - test
  - build
  - release
  - deploy

###### JOBS ###################################################################
install:
  <<: *general
  stage: install
  cache:
    policy: pull-push
    paths:
      - node_modules
  script:
    - yarn install
  only:
    - master

test:
  <<: *general
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - install
  artifacts:
    paths:
      - coverage
    expire_in: 1 month
  script:
    - yarn test --verbose --forceExit --ci --coverage --colors
  only:
    - master

build:
  <<: *general
  stage: build
  environment:
    name: ${CI_COMMIT_REF_NAME}
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - install
  script:
    - yarn react-build
  artifacts:
    expire_in: 1 week
    paths:
      - build
  only:
    - master

release:mac:
  <<: *release-common
  tags:
    - macos
  script:
    - yarn dist -m --publish always

release:linux:
  <<: *release-common
  image: electronuserland/builder:10
  script:
    - yarn dist -l --publish always

release:windows:
  <<: *release-common
  image: electronuserland/builder:wine
  script:
    - yarn dist -w --publish always

pages:
  <<: *general
  stage: deploy
  cache:
    policy: pull
    paths: []
  dependencies: []
  script:
    - cd pages
    - yarn install
    - yarn build
    - rm -rf ../public
    - mv build ../public
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  only:
    - master
