image: node:8.11.2

pages:
  stage: deploy
  script:
    - cd pages
    - yarn install
    - yarn build
    - ls -la
    - ls -la build
    - pwd
  artifacts:
    paths:
    - build
  only:
    - dev
