###### GENERAL ################################################################
image: node:8.11.2

cache:
  paths:
  - node_modules/
  - pages/node_modules/

###### STAGES #################################################################
stages:
  - install
  - test
  - build
  - publish

###### JOBS ###################################################################
license_management:
  image:
    name: "registry.gitlab.com/gitlab-org/security-products/license-management:$CI_SERVER_VERSION_MAJOR-$CI_SERVER_VERSION_MINOR-stable"
    entrypoint: [""]
  stage: test
  allow_failure: true
  script:
    - /run.sh analyze .
  artifacts:
    reports:
      license_management: gl-license-management-report.json

pages:
  stage: deploy
  script:
    - cd pages
    - yarn install
    - yarn build
    - rm -rf ../public
    - mv build ../public
  artifacts:
    paths:
    - public
  only:
    - master
