image: node:8.11.2

pages:
  stage: deploy
  cache:
    paths:
    - pages/node_modules/
  script:
    - cd pages
    - yarn install
    - yarn build
    - rm -rf ../public
    - mv build ../public
  artifacts:
    paths:
    - public
  only:
    - dev
