## https://docs.gitlab.com/ce/ci/yaml/README.html

###### GENERAL ################################################################
image: node:12.14.1

cache:
  paths:
  - node_modules/
  - pages/node_modules/

###### TEMPLATES ##############################################################
.general: &general
  tags:
    - gitlab-org
  variables:
    GIT_STRATEGY: fetch
  only:
    - branches
  except:
    - /^v.*$/

.release-common: &release-common
  <<: *general
  stage: release
  cache:
    policy: pull
    paths: []
  dependencies:
    - react app
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - release
  retry:
    max: 2
    when: always

###### STAGES #################################################################
stages:
  - install
  - test
  - build
  - pre-release
  - release
  - deploy

###### JOBS ###################################################################
dependencies:
  <<: *general
  stage: install
  cache:
    policy: pull-push
    paths:
      - node_modules
  script:
    - yarn install

jest:
  <<: *general
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - dependencies
  artifacts:
    paths:
      - coverage
    expire_in: 1 month
  script:
    - yarn test --verbose --forceExit --ci --coverage --colors

react app:
  <<: *general
  stage: build
  environment:
    name: ${CI_COMMIT_REF_NAME}
  cache:
    policy: pull
    paths:
      - node_modules
  dependencies:
    - dependencies
  script:
    - echo "NODE_ENV=production" > .env
    - echo "CLIENT_SECRET=${CLIENT_SECRET}" >> .env
    - echo "REACT_APP_PRODUCT_NAME=${npm_package_productName}" >> .env
    - yarn react-build
  artifacts:
    expire_in: 1 week
    paths:
      - .env
      - build
  only:
    - master
    - release

tag version:
  <<: *general
  stage: pre-release
  environment:
    name: ${CI_COMMIT_REF_NAME}
  cache:
    policy: pull
    paths: []
  dependencies: []
  script:
    - mkdir -p ~/.ssh
    - echo "${SSH_KEY}" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - echo "Host gitlab.com" > ~/.ssh/config
    - echo " IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
    - git config --global user.name "Slothy CI/CD"
    - git config --global user.email "3884597-slothy-cicd@users.noreply.gitlab.com"
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - git remote remove origin
    - git remote add gitlab https://slothy-cicd:${GITLAB_TOKEN}@gitlab.com/kirbo/slothy.git
    - yarn create-tag
    - git push gitlab --tags -o ci.skip
  only:
    - release

mac:
  <<: *release-common
  tags:
    - macos
  script:
    - yarn
    - yarn dist -m --publish always

linux:
  <<: *release-common
  image: kirbownz/electron-builder-node:latest
  script:
    - yarn
    - yarn dist -l --publish always

windows:
  <<: *release-common
  image: kirbownz/electron-builder-wine:latest
  script:
    - yarn
    - yarn dist -w --publish always

pages:
  <<: *general
  stage: deploy
  cache:
    policy: pull
    paths: []
  dependencies: []
  script:
    - cd pages
    - yarn install
    - yarn build
    - rm -rf ../public
    - mv build ../public
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  only:
    - release
